image: node:10.13.0

stages:
    - install
    - test

install:
    stage: install
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    script:
        - npm run test


